### ISSUE TITLE
请问可以做kibana的cas认证吗

### ISSUE THREAD

**Issue by BigbigY** [chenryn/ELKstack-guide-cn#29]
看到博主这篇文章，https://github.com/chenryn/ELKstack-guide-cn/blob/master/kibana/v3/auth/nodejs-cas.md

对此不是很明白，除了标题是kibana的认证，但是内容和代码中都是es的代理认证

**Comment by chenryn** [comment]
这篇文章里，主要内容是kibana-authentication-proxy项目的配置。实际实现都在这个项目里。因为是现成的项目，作者就没具体介绍了。毕竟本书以使用场景介绍为目的。
